### PR TITLE
ViewActivity updates

### LINKED ISSUE #72: Crash using intents
repro
aperture -> take photo/video
open video/photo via thunbnail -> select glimpse
glimpse -> delete video/photo ( app closes )
open video/photo via thunbnail -> select glimpse
glimpse -> boom

### PR DESCRIPTION
**Pull request by SebaUbuntu**
Fixes: https://github.com/lineage-next/android_packages_apps_Glimpse/issues/72

### CODE REVIEW

File: app/src/main/java/org/lineageos/glimpse/ViewActivity.kt [hunk 1]
```diff
@@ -54,118 +306,363 @@ class ViewActivity : AppCompatActivity() {
...
+                    contentResolver.createFavoriteRequest(
+                        !it.isFavorite, it.externalContentUri
+                    )
+                )
+            }
+        }
+
+        shareButton.setOnClickListener {
+            mediaUri?.also {
+                val intent = buildShareIntent(it)
```
Comment (luk1337) [inline app/src/main/java/org/lineageos/glimpse/ViewActivity.kt]: would probably inline both intents

File: app/src/main/java/org/lineageos/glimpse/ViewActivity.kt [hunk 2]
```diff
@@ -54,118 +306,363 @@ class ViewActivity : AppCompatActivity() {
...
+            mediaViewerAdapter.getItemAtPosition(viewPager.currentItem).let {
+                MediaInfoBottomSheetDialog(
+                    this, it, mediaInfoBottomSheetDialogCallbacks, secure
+                ).show()
+            }
+        }
+
+        adjustButton.setOnClickListener {
+            mediaViewerAdapter.getItemAtPosition(viewPager.currentItem).let {
+                val intent = buildEditIntent(it)
```
Comment (luk1337) [inline app/src/main/java/org/lineageos/glimpse/ViewActivity.kt]: here too

File: app/src/main/java/org/lineageos/glimpse/fragments/AlbumFragment.kt [hunk 3]
```diff
@@ -72,10 +75,12 @@ class AlbumFragment : Fragment(R.layout.fragment_album) {
...
-            findNavController().navigate(
-                R.id.action_albumFragment_to_mediaViewerFragment,
-                MediaViewerFragment.createBundle(media, album.id)
-            )
+            val intent = Intent(requireContext(), ViewActivity::class.java).apply {
+                action = MediaStore.ACTION_REVIEW
+                data = media.externalContentUri
+                putExtra(ViewActivity.KEY_ALBUM_ID, album.id)
+            }
+            startActivity(intent)
```
Comment (luk1337) [inline app/src/main/java/org/lineageos/glimpse/fragments/AlbumFragment.kt]: inline intent

File: app/src/main/java/org/lineageos/glimpse/fragments/ReelsFragment.kt [hunk 4]
```diff
@@ -74,10 +71,12 @@ class ReelsFragment : Fragment(R.layout.fragment_reels) {
...
-            parentNavController.navigate(
-                R.id.action_mainFragment_to_mediaViewerFragment,
-                MediaViewerFragment.createBundle(media, MediaStoreBuckets.MEDIA_STORE_BUCKET_REELS.id)
-            )
+            val intent = Intent(requireContext(), ViewActivity::class.java).apply {
+                action = MediaStore.ACTION_REVIEW
+                data = media.externalContentUri
+                putExtra(ViewActivity.KEY_ALBUM_ID, MediaStoreBuckets.MEDIA_STORE_BUCKET_REELS.id)
+            }
+            startActivity(intent)
```
Comment (luk1337) [inline app/src/main/java/org/lineageos/glimpse/fragments/ReelsFragment.kt]: inline

File: app/src/main/java/org/lineageos/glimpse/ViewActivity.kt [hunk 5]
```diff
@@ -54,118 +306,363 @@ class ViewActivity : AppCompatActivity() {
...
+        this.additionalMedias = additionalMedias
+        this.mediaUri = mediaUri
+        this.secure = secure
+
+        // Update UI while at it
+        runOnUiThread {
+            updateUI()
+        }
+
+        return true
```
Comment (luca020400) [inline app/src/main/java/org/lineageos/glimpse/ViewActivity.kt]: always true?

File: app/src/main/java/org/lineageos/glimpse/ViewActivity.kt (hunk 1 above)
Comment (SebaUbuntu) [reply app/src/main/java/org/lineageos/glimpse/ViewActivity.kt]: Done

File: app/src/main/java/org/lineageos/glimpse/fragments/AlbumFragment.kt (hunk 3 above)
Comment (SebaUbuntu) [reply app/src/main/java/org/lineageos/glimpse/fragments/AlbumFragment.kt]: Done

File: app/src/main/java/org/lineageos/glimpse/ViewActivity.kt (hunk 2 above)
Comment (SebaUbuntu) [reply app/src/main/java/org/lineageos/glimpse/ViewActivity.kt]: Done

File: app/src/main/java/org/lineageos/glimpse/fragments/ReelsFragment.kt (hunk 4 above)
Comment (SebaUbuntu) [reply app/src/main/java/org/lineageos/glimpse/fragments/ReelsFragment.kt]: Done

File: app/src/main/java/org/lineageos/glimpse/ViewActivity.kt (hunk 5 above)
Comment (SebaUbuntu) [reply app/src/main/java/org/lineageos/glimpse/ViewActivity.kt]: Moved return value to each intent handler method

File: app/src/main/java/org/lineageos/glimpse/recyclerview/ThumbnailAdapter.kt [hunk 6]
```diff
@@ -82,66 +63,54 @@ class ThumbnailAdapter(
...
-        }
-
-        val previousPosition = position - 1
+    override fun getItemViewType(position: Int) = data[position].viewType
 
-        if (headersPositions.contains(previousPosition)) {
-            // Before this position we have a header, next up there's a thumbnail
-            return ViewTypes.ITEM.ordinal
-        }
+    fun setMedias(medias: Array<Media>) {
```
Comment (luca020400) [inline app/src/main/java/org/lineageos/glimpse/recyclerview/ThumbnailAdapter.kt]: Move that logic in the view model.
Doing modeling has no business in the view.

Comment (SebaUbuntu) [reply app/src/main/java/org/lineageos/glimpse/recyclerview/ThumbnailAdapter.kt]: Done

File: app/src/main/java/org/lineageos/glimpse/viewmodels/ThumbnailViewModel.kt [hunk 7]
```diff
@@ -0,0 +1,94 @@
...
+        initialValue = QueryResult.Empty(),
+    )
+
+    sealed class DataType(val id: Long, val viewType: Int) {
+        class Thumbnail(val media: Media) : DataType(media.id, ThumbnailAdapter.ViewTypes.THUMBNAIL.ordinal) {
+            override fun equals(other: Any?) = media == other
+            override fun hashCode() = media.hashCode()
+        }
+
+        class DateHeader(val date: Date) : DataType(-date.time, ThumbnailAdapter.ViewTypes.DATE_HEADER.ordinal) {
```
Comment (luca020400) [inline app/src/main/java/org/lineageos/glimpse/viewmodels/ThumbnailViewModel.kt]: This may not work, Java doesn't have unsigned types so mediaID can be negative ( and is negative )
We need to come up with something unique or use diff util rather than stable ids

Comment (SebaUbuntu) [reply app/src/main/java/org/lineageos/glimpse/viewmodels/ThumbnailViewModel.kt]: Done

**Review by luca020400 — APPROVED** [review]

**Comment by SebaUbuntu** [comment]
lgtm
